env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
language: node_js
node_js:
- '0.12.4'
before_install:
- npm install -g gulp
- npm install
script:
- gulp test
deploy:
  provider: npm
  email: yosuke.kurami@gmail.com
  api_key:
    secure: Qco1+HhARox86Apkz63dh/KBusR00Cut8MbzK20jIzPkU7PzViK6E1QNtHe3p6O0UMKVjbNr1mdJJq0t7Gnj/824fqwe4VFWiIqK6nBOOumgq3hP+1lrDRb9shHVtZr4vlCw8KhO9XmigHZ2Ey0F5/tj0RF+Wd/L6o1jCFZrHXY=
  on:
    tags: true
    repo: Quramy/electron-connect
    all_branches: true
